# action.yml
name: 'build-fuzzers'
description: "Builds an OSS-Fuzz project's fuzzers."
inputs:
  oss-fuzz-project-name:
    description: 'Name of the corresponding OSS-Fuzz project.'
    required: true
  dry-run:
    description: 'If set, run the action without actually reporting a failure.'
    default: false
  allowed_broken_targets_percentage:
    description: 'Name of the corresponding OSS-Fuzz project.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OSS_FUZZ_PROJECT_NAME: ${{ inputs.oss-fuzz-project-name }}
    DRY_RUN: ${{ inputs.dry-run}}
